# Generated by Django 2.2 on 2019-07-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(default='makah', max_length=100),
        ),
    ]
