# Generated by Django 2.2 on 2019-07-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_pay_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('1', 'Cash On Delivery'), ('2', 'PayPal')], default='Cash On ..', max_length=100, null=True),
        ),
    ]
