# Generated by Django 2.2 on 2019-07-04 21:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0013_auto_20190702_0843'),
        ('cart', '0005_auto_20190705_0128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopingCart',
            new_name='Cart',
        ),
    ]
