# Generated by Django 2.2 on 2019-07-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20190705_0144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
