# Generated by Django 2.2.2 on 2019-06-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='caliber',
            field=models.PositiveIntegerField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.FloatField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=True),
        ),
    ]
