# Generated by Django 2.2 on 2019-06-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190624_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Category',
            field=models.CharField(choices=[('sets', 'sets'), ('half sets', 'half sets'), ('nechlace', 'nechlace'), ('rings', 'rings'), ('earrings', 'earrigs'), ('bracelets', 'bracelets')], default='sets', max_length=9),
        ),
    ]
