# Generated by Django 2.2 on 2019-06-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category',
            new_name='Choices',
        ),
    ]
