# Generated by Django 2.2 on 2019-06-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190624_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Choices',
        ),
        migrations.AddField(
            model_name='product',
            name='Choices',
            field=models.CharField(choices=[('sets', 'sets'), ('half sets', 'half sets'), ('nechlace', 'nechlace'), ('rings', 'rings'), ('earrings', 'earrigs'), ('bracelets', 'bracelets')], default='sets', max_length=9),
        ),
    ]
