# Generated by Django 2.2 on 2019-06-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190625_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Choices',
            field=models.CharField(choices=[('s', 'sets'), ('hs', 'half sets'), ('n', 'nechlace'), ('r', 'rings'), ('e', 'earrigs'), ('b', 'bracelets')], default='sets', max_length=9),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
