# Generated by Django 2.2 on 2019-07-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20190628_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Choices',
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default='static/img/default.png', upload_to=''),
        ),
    ]
