# Generated by Django 2.2 on 2019-07-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20190702_0843'),
        ('accounts', '0002_auto_20190703_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ebook',
            field=models.ManyToManyField(blank=True, to='shop.Product'),
        ),
    ]
