# Generated by Django 2.2 on 2019-07-04 20:12

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('accounts', '0003_profile_ebook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ebook',
            new_name='products',
        ),
    ]
